### ISSUE TITLE
Audio Issues (Weapons, Footsteps)

### ISSUE THREAD

**Issue by Gingrvitis** [Althro/Tinvaak#12]
I just downloaded the modlist today, and it's absolutely gorgeous, the only issue I have encountered so far, is not having the audio for Sheathing/Unsheathing your weapon, no footstep audio (NPC, Creature, or Self), there is the occasional footstep audio when jumping and landing, but it's inconsistent. I've turned my audio footstep sliders up all the way and still the same issue. Any help is solving this would be grand, I am running with a Logitech 5.1 or 7.1 headset, which could be the issue, but I'm unaware of how to fix that, but figured I'd come here and ask if there is something, someone might know to help me.

Thank you in advance!

Edit:  Upon further playing, there is no sound to anything related to weapons (killmoves, attacking, swinging, blocking, swapping)

**Comment by Althro** [comment]
This is puzzling on sounds. I've gotten a simiilar report about this and when testing on my end, everything has seemed fine. Where do you have the list installed and what weapons have you been using?

**Comment by Althro** [comment]
Please try the following:

> After completing the Lexy LOTD build, but can not hear most of the combat sounds such as swings a sword, use a spell (ex: flame, heal, etc.), opens a container, footsteps, etc. However, talking to NPCs, drawing or sheathing a sword and wolves in the background sounds did work. It seemed to stump everyone. It took a while, but found the solution. Apparently, if you install Steam on an alternate drive other then C:, this was a known issue. If you do not want to reinstall the build on you C: drive, a quick fix originally posted by Kepache is as follows:

> "1. First download and install Link Shell Extension which can be found here: http://schinagl.priv.at/nt/hardlinkshellext/linkshellextension.html.

> 2. Navigate to your Skyrim/Data folder and look for a file named Skyrim - Sounds.bsa. Copy this file and paste it somewhere on your main drive.

> 3. Delete Skyrim - Sounds.bsa from the Data folder.

> 4. Go back to where you copied Skyrim - Sounds.bsa on your main drive. Right click on it and you should see an option that says "Pink Link Source". Click that.

> 5. Go back to your Skyrim/Data folder. Right click anywhere and choose "Drop As" and then "Symbolic Link". You will see your sounds file with a shortcut symbol. You know it works when you do."

> However, for the Lexy LOTD build, I figure out the hard way that the above is not enough. You also need to do the above for the Skyrim - Voices_en0.bsa also found in the Skyrim Data folder, Audio Overhaul Skyrim for SE sound folder, Immersive Sound - Compendium sound folder, Lucidity sound folder and the Unofficial High Definition Audio Project bsa files which are found in their respected MO2 mod folders. Problem solved!

Whilst this was done for Lexy's, this fix does work for other modlists.

**Comment by Althro** [comment]
Closing this issue as I'm 90% sure it's fixed by that. Will reopen if needed.
