### ISSUE TITLE
3rd person bow sneak animation is very wonky 

### ISSUE THREAD

**Issue by cheesemanhugs** [Althro/Tinvaak#14]
![The Elder Scrolls V  Skyrim Special Edition Screenshot 2021 05 14 - 02 22 15 77](https://user-images.githubusercontent.com/64744940/118230239-55d55500-b45b-11eb-87ea-fa8ba678740d.png)

**Comment by Althro** [comment]
Known issue, will fix in 2.0 by removal of this mod.
