### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by psyops78** [Althro/Tinvaak#17]
Hi, Was trying to give the modpack a go but getting this error with some main .esm files download when trying to install. Legit copy of SE on Steam. Log shows:

0.83 - Wabbajack Version: 2.4.4.2
1.55 - Build server is alive
1.55 - File hash check (-42) 38a5ae3545184ddd7b68c22e7d2d069a47fedc66108669c7f3fef8d400bb182e
1.57 - Build server is alive
1.57 - File hash check (-42) 38a5ae3545184ddd7b68c22e7d2d069a47fedc66108669c7f3fef8d400bb182e
24.86 - Starting to install Tinvaak
24.87 - Cleaning VFS, this may take a bit of time
24.89 - Starting Installer Task
24.89 - Installation has Started
24.89 - File hash check (-42) 38a5ae3545184ddd7b68c22e7d2d069a47fedc66108669c7f3fef8d400bb182e
25.53 - Configuring Processor
25.54 - Install Folder: G:\TINVAAK SE
25.54 - Downloads Folder: G:\TINVAAK SE\downloads
25.54 - Game Folder: G:\XXXXXX\steamapps\common\Skyrim Special Edition
25.54 - Wabbajack Folder: G:\Wabbajack\2.4.4.3
25.54 - Drive watcher is starting. Will warn at 8GB and error at 4GB
25.54 - Starting Drive watcher on G:\ currently 55.7GB free out of 931.5GB
25.55 - Validating Game ESMs
25.55 - Creating Output Folders
26.33 - Optimizing ModList
26.33 - Optimizing ModList directives
27.99 - Looking for files to delete
28.04 - Cleaning empty folders
28.66 - Looking for unmodified files
28.97 - Updating ModList
28.97 - Optimized 99074 directives to 99074 required
29.02 - Hashing Archives
29.03 - Looking for files to hash
29.14 - Found 1251 total files, 757 matching filesize
562.67 - Downloading Missing Archives
562.67 - Missing 4 archives
562.67 - Getting Nexus API Key, if a browser appears, please accept
562.7 - Loading server whitelist
563.08 - Loaded permissions for 439 servers and 179 Google Drive files
563.08 - File hash check (-42) 38a5ae3545184ddd7b68c22e7d2d069a47fedc66108669c7f3fef8d400bb182e
563.1 - Downloading Data_Update.esm
563.11 - Downloading Data_HearthFires.esm
563.11 - Downloading Data_Dragonborn.esm
563.13 - Downloading Data_Dawnguard.esm
563.21 - Hashed download is incorrect
563.49 - Hashed download is incorrect
563.63 - Hashed download is incorrect
563.85 - Trying to find solution to broken download for Data_HearthFires.esm
563.85 - Looking for generic upgrade for GPdcQrqi2NI= (-3253671809914177768)
564.13 - Trying to find solution to broken download for Data_Update.esm
564.13 - Looking for generic upgrade for /DLG/LjdGXI= (8221846381326119676)
564.2 - Hashed download is incorrect
564.26 - Trying to find solution to broken download for Data_Dawnguard.esm
564.26 - Looking for generic upgrade for CEgEhUUtOcU= (-4235304197957597176)
564.51 - Looking for generic upgrade for GPdcQrqi2NI= (-3253671809914177768)
564.52 - Looking for generic upgrade for CEgEhUUtOcU= (-4235304197957597176)
564.81 - Looking for generic upgrade for /DLG/LjdGXI= (8221846381326119676)
564.84 - Trying to find solution to broken download for Data_Dragonborn.esm
564.84 - Looking for generic upgrade for eypuUwdQUb4= (-4732913740994958725)
565.14 - No solution for broken download Data_HearthFires.esm GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\hearthfires.esm could be found
565.2 - No solution for broken download Data_Dawnguard.esm GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\dawnguard.esm could be found
565.45 - No solution for broken download Data_Update.esm GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\update.esm could be found
565.48 - Looking for generic upgrade for eypuUwdQUb4= (-4732913740994958725)
565.74 - No solution for broken download Data_Dragonborn.esm GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\dragonborn.esm could be found
566.06 - Hashing Remaining Archives
566.06 - Looking for files to hash
566.2 - Found 1251 total files, 757 matching filesize
566.38 - Unable to download Data_Dawnguard.esm (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\dawnguard.esm)
566.38 - Unable to download Data_Dragonborn.esm (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\dragonborn.esm)
566.38 - Unable to download Data_HearthFires.esm (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\hearthfires.esm)
566.38 - Unable to download Data_Update.esm (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\update.esm)
566.38 - Cannot continue, was unable to download one or more archives
566.39 - File hash check (-42) 38a5ae3545184ddd7b68c22e7d2d069a47fedc66108669c7f3fef8d400bb182e
566.39 - Vacuuming databases
567.1 - File hash check (-42) 38a5ae3545184ddd7b68c22e7d2d069a47fedc66108669c7f3fef8d400bb182e
567.11 - Vacuuming completed
567.12 - Encountered error, can't continue - System.Exception: Cannot continue, was unable to download one or more archives
   at Wabbajack.Lib.AInstaller.Error(String msg) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\AInstaller.cs:line 69
   at Wabbajack.Lib.MO2Installer._Begin(CancellationToken cancel) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\MO2Installer.cs:line 156
   at Wabbajack.Lib.ABatchProcessor.<Begin>b__66_0() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\ABatchProcessor.cs:line 177
   at Wabbajack.MO2InstallerVM.<>c__DisplayClass31_0.<<Install>b__0>d.MoveNext() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 181
--- End of stack trace from previous location ---
   at Wabbajack.MO2InstallerVM.Install() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 175
   at Wabbajack.InstallerVM.<>c__DisplayClass85_0.<<-ctor>b__75>d.MoveNext() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\InstallerVM.cs:line 373

*************************

Any help would be appreciated. Thanks!

**Comment by Althro** [comment]
Verify your game files with steam. Also, you have nowhere near enough space on that drive to install it. You need **at least** 150GB space for both the list, downloads and working area so that WJ can process things.

**Comment by psyops78** [comment]
Free'd up some space as didn't notice drive was filling up and checked game files and all good now. Game installed with no further issues. Thanks for the help! Looking forward to trying your modlist out ;)
