### ISSUE TITLE
game closes when loading (when i finish the character and starts loading)

### ISSUE THREAD

**Issue by jocira** [Althro/Tinvaak#18]
[Crash_2021_6_27_10-57-56.txt](https://github.com/Althro/Tinvaak/files/6728832/Crash_2021_6_27_10-57-56.txt)
[Crash_2021_6_28_21-20-22.txt](https://github.com/Althro/Tinvaak/files/6728833/Crash_2021_6_28_21-20-22.txt)
[Crash_2021_6_28_21-28-9.txt](https://github.com/Althro/Tinvaak/files/6728834/Crash_2021_6_28_21-28-9.txt)

**Comment by Althro** [comment]
That's not what I'm after. Ensure that you have copied the game folder files across and if you still crash, please post the **crashlog** not the modlist.txt.

**Comment by jocira** [comment]
> That's not what I'm after. Ensure that you have copied the game folder files across and if you still crash, please post the **crashlog** not the modlist.txt. Follow the issue template.

sorry, english isnt my main language, hard to understand the instructions

**Comment by Althro** [comment]
From looking at the logs, it appears that there may be an issue with your nvidia graphics driver. I'd advise going back to an earlier version if you have updated them recently.

**Comment by Althro** [comment]
Either that, or your audio device is having issues.

**Comment by jocira** [comment]
Ty very much, i Will try it tomorrow because its late here, i Will tell u
if it works in te forum

**Comment by jocira** [comment]
didnt work

**Comment by Althro** [comment]
Are you running this per chance via an emulator on another operating system?

**Comment by jocira** [comment]
Nope, Just a PC With windows
