### ISSUE TITLE
Unable to download Tinvaak DYNDOLOD Output

### ISSUE THREAD

**Issue by SwordShaman** [Althro/Tinvaak#19]
I've been trying to download the modlist through Wabbajack for about three days.  Every file except Tinvaak DYNDOLOD Output have completed successfully.  It fails at this file every time.  I've tried deleting the partially downloaded file and restarting Wabbajack several times.  Wondering if there's a manual method to download this file.

**Comment by Althro** [comment]
There are mirrors to the links in my server and you can try the network workaround mode. I'd wait though aas there's a new update coming probably tonight.
