### ISSUE TITLE
After every death, all my saves are corrupted.

### ISSUE THREAD

**Issue by Glipngr** [Althro/Tinvaak#2]
My game did not crash, so i have no crashlog to upload here, however it is still an issue i have not had with any other modpacks made uploaded on Wabbajack, so i figured id report it.

The only mods i have are the ones that come in the Tinvaak modpack, as i have not added or removed any.

[modlist.txt](https://github.com/Althro/Tinvaak/files/6176718/modlist.txt)

After my character dies, no matter how, the camera remains on my characters corpse, not reloading to an older save. If I try to manually load an older save, it tells me the save is corrupted, therefore losing the character altogether.

Make a save, play for a little bit, then die and see if your saves are corrupted.
If you want specifics, i started in Falkreath after creating my character through Unbound, assigned the attributes, and used the Wildcat power.

I did not expect my saves to constantly corrupt.

Whatever version the modlist was at as of 03/20/2021

I did not add any additional mods.

![corrupted](https://user-images.githubusercontent.com/81060903/111892102-729e6080-89b5-11eb-99a4-b4559a688249.jpg)

![dead](https://user-images.githubusercontent.com/81060903/111892104-7500ba80-89b5-11eb-87a6-524ad3abe8bc.jpg)

I know this is only 1 instance shown, but i assure you ive tried 3 different saves, all with this happening.

**Comment by Althro** [comment]
I saw your posts in the WJ main discord about you having not copied the game folder files correctly. Copying the GFF correctly (as mentioned in this part of the readme: https://github.com/Althro/Tinvaak#game-folder-files) will resolve this.
