### ISSUE TITLE
Repeatable Crash with some merchant NPCs

### ISSUE THREAD

**Issue by phinocio** [Althro/Tinvaak#21]
**Upload your crashlog**

[Crash_2021_8_9_22-8-23.txt](https://github.com/Althro/Tinvaak/files/6958978/Crash_2021_8_9_22-8-23.txt)

**Required: Modlist.txt**

[modlist.txt](https://github.com/Althro/Tinvaak/files/6958979/modlist.txt)

**Describe the bug**
When activating a merchant to buy items, it crashes the game. Per the crash log, likely to do with Feather spell tome. Affected NPCs so far include Mithllon and Farengar, though likely any pulling from that levelled list. 

**To Reproduce**

1. Go to Mithllon in Whiterun
2. Try to open the barter menu to by something
3. Game crashes

**Expected behavior**
Game not crashing and the barter menu opening.

**Screenshots**
N/A

**Modlist version**
v1.6

**Did you add any additional mods?**
Nay, clean install from WJ earlier after updating the list didn't work for me.

***YOU MUST DECLARE IF YOU HAVE MODIFIED THE LIST.***
Nay x2 :P

**Comment by Althro** [comment]
Thanks for the report, I've got this fixed for the next update.
