### ISSUE TITLE
Clefj's Winterhold - Frozen Hearth

### ISSUE THREAD

**Issue by Codygits** [Althro/Tinvaak#22]
Floating Items in Frozen Hearth Main Building

![enb2021_8_10_01_45_13](https://user-images.githubusercontent.com/20106025/128820918-7528cc2e-763e-40ed-a535-1a96eaeb3d8b.jpg)
![enb2021_8_10_01_45_24](https://user-images.githubusercontent.com/20106025/128820926-9d42bc8b-a9e1-4811-adfa-778153a4cb47.jpg)

**Comment by Althro** [comment]
Thanks for the report, I've got these fixed for the new version.
