### ISSUE TITLE
Wabberjack installation failing

### ISSUE THREAD

**Issue by Relendis** [Althro/Tinvaak#3]
Installing Tinvaak on Wabberjack I am getting an error which is causing the installation to fail at the Downloading Missing Archives stage.  It is reporting in the console that it is unable to download Skyrim_Particle _Patch_for_ENB-SSE.

1.53 - Build server is alive
1.53 - File hash check (-42) 7a3d7bd520cfb28a1c8dd7ac5eadf0edf21284d4bc53a281e61954cedb40bddd
16.25 - Starting to install Tinvaak
16.26 - Cleaning VFS, this may take a bit of time
16.28 - Starting Installer Task
16.28 - Installation has Started
16.28 - File hash check (-42) 7a3d7bd520cfb28a1c8dd7ac5eadf0edf21284d4bc53a281e61954cedb40bddd
17.16 - Configuring Processor
17.17 - Install Folder: C:\Modlists\Tinvaak
17.17 - Downloads Folder: C:\Modlists\Tinvaak\downloads
17.17 - Game Folder: c:\program files (x86)\steam\steamapps\common\Skyrim Special Edition
17.17 - Wabbajack Folder: C:\Wabbajack
17.17 - Drive watcher is starting. Will warn at 8GB and error at 4GB
17.17 - Starting Drive watcher on C:\ currently 147.5GB free out of 953.3GB
17.17 - Starting Drive watcher on c:\ currently 147.5GB free out of 953.3GB
17.18 - Validating Game ESMs
17.18 - Creating Output Folders
17.26 - Optimizing ModList
17.26 - Optimizing ModList directives
18.32 - Looking for files to delete
18.33 - Cleaning empty folders
18.73 - Looking for unmodified files
18.96 - Updating ModList
18.96 - Optimized 99075 directives to 99075 required
19 - Hashing Archives
19 - Looking for files to hash
19.08 - Found 811 total files, 756 matching filesize
19.22 - Downloading Missing Archives
19.22 - Missing 1 archives
19.22 - Getting Nexus API Key, if a browser appears, please accept
19.23 - Loading server whitelist
19.37 - Loaded permissions for 416 servers and 165 Google Drive files
19.37 - File hash check (-42) 7a3d7bd520cfb28a1c8dd7ac5eadf0edf21284d4bc53a281e61954cedb40bddd
19.41 - Downloading Skyrim_Particle_Patch_for_ENB-SSE.zip
35.79 - Hashed download is incorrect
36.68 - Trying to find solution to broken download for Skyrim_Particle_Patch_for_ENB-SSE.zip
36.68 - Looking for generic upgrade for wBU8xmp6w4Y= (-8736004253157681728)
37.68 - Looking for generic upgrade for wBU8xmp6w4Y= (-8736004253157681728)
38.56 - No solution for broken download Skyrim_Particle_Patch_for_ENB-SSE.zip GoogleDriveDownloader+State|12tL3_kpm_KXlQvQqEnK3zOAl-sm_H3Fw could be found
38.59 - Hashing Remaining Archives
38.59 - Looking for files to hash
38.65 - Found 811 total files, 756 matching filesize
38.76 - Unable to download Skyrim_Particle_Patch_for_ENB-SSE.zip (GoogleDriveDownloader+State|12tL3_kpm_KXlQvQqEnK3zOAl-sm_H3Fw)
38.76 - Cannot continue, was unable to download one or more archives
38.76 - File hash check (-42) 7a3d7bd520cfb28a1c8dd7ac5eadf0edf21284d4bc53a281e61954cedb40bddd
38.76 - Vacuuming databases
38.77 - Vacuuming completed
38.78 - Encountered error, can't continue - System.Exception: Cannot continue, was unable to download one or more archives
   at Wabbajack.Lib.AInstaller.Error(String msg) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\AInstaller.cs:line 69
   at Wabbajack.Lib.MO2Installer._Begin(CancellationToken cancel) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\MO2Installer.cs:line 156
   at Wabbajack.Lib.ABatchProcessor.<Begin>b__66_0() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\ABatchProcessor.cs:line 177
   at Wabbajack.MO2InstallerVM.<>c__DisplayClass31_0.<<Install>b__0>d.MoveNext() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 181
--- End of stack trace from previous location ---
   at Wabbajack.MO2InstallerVM.Install() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 175
   at Wabbajack.InstallerVM.<>c__DisplayClass85_0.<<-ctor>b__75>d.MoveNext() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\InstallerVM.cs:line 373
39.65 - File hash check (-42) 7a3d7bd520cfb28a1c8dd7ac5eadf0edf21284d4bc53a281e61954cedb40bddd

**Comment by Althro** [comment]
That is due to the Particle patch updating. There is a mirror in #serenity-support in the main Wabbajack discord. I will fix this soon.

**Comment by Relendis** [comment]
Cheers mate, all sorted and closed.
