### ISSUE TITLE
question regarding spiders

### ISSUE THREAD

**Issue by gustlik** [Althro/Tinvaak#4]
Hi,
i would like to play your mod compilation but the problem is that i hate spiders. I wanted to use mode like: https://www.nexusmods.com/skyrimspecialedition/mods/37319
Could you please confirm how should i achieve it? I mean will it be enough to disable conflicting mods like better spider webs for enb and enable that one or it would be more complicated. 
Thank you.

**Comment by Althro** [comment]
Hello there. This isn't really the place for things like this, but a check in xEdit would confirm to you whether you can or not.

There's quite a few good guides out there on how to check for conflicts, with this one in particular being a very good one: https://github.com/LivelyDismay/Learn-To-Mod/wiki/xEdit-Lessons

In short, you'd need to add the mod, move it to the appropriate place in the left pane of MO2 and then move it in the right pane. Check in xEdit for coflicts and resolve any that arise. You will likely need to redo the Reproccer, NPC health Rescaler and Synthesis patcher. The first 2 are done via UPF loaders generated via xEdit with the latter just being a simple re-run.

For further discussion around this, I would advise you join my discord server and post in #list-modifications.

**Comment by gustlik** [comment]
I cant find mentioned discord server. Could you provide link for it ?

**Comment by Althro** [comment]
It's accessible via the main Wabbajack server. I prefer to not direct link now, but maybe in the future.

**Comment by gustlik** [comment]
I thought that it will be in discord-links section but i cant find anything with your name or mod name there.

**Comment by Althro** [comment]
It's linked in #tinvaak

**Comment by gustlik** [comment]
so it seems that I cant see it or i cant use it
![obraz](https://user-images.githubusercontent.com/689938/115295048-9e9a3680-a159-11eb-957d-bdded69eeda1.png)

**Comment by Althro** [comment]
You need to verify yourself and get game roles iin the server. Have a read of the welcome channel.

**Comment by Althro** [comment]
> There's quite a few good guides out there on how to check for conflicts, with this one in particular being a very good one: https://github.com/LivelyDismay/Learn-To-Mod/wiki/xEdit-Lessons
> 
> In short, you'd need to add the mod, move it to the appropriate place in the left pane of MO2 and then move it in the right pane. Check in xEdit for coflicts and resolve any that arise. You will likely need to redo the Reproccer, NPC health Rescaler and Synthesis patcher. The first 2 are done via UPF loaders generated via xEdit with the latter just being a simple re-run.

There are these guides to follow if you wish to have a try yourself.
