### ISSUE TITLE
Vanilla fire spells not dealing any damage

### ISSUE THREAD

**Issue by JoliusI** [Althro/Tinvaak#7]
Hello.
So i have been playing with the modlist for a while now and i seem to be encountering a problem concerning the vanilla fire spell.
It seems as though spells like fireball, greater fire rune, incinerat and a few others.
It looks like the perk effects are still working but there is just no damage being done from the impact.
It looks like it's mostly vanilla spells that are the problem but I do not know if the same is for the ice and lightning spells.
Is there anything that I could try and fix this problem

Best regards.

**Comment by Althro** [comment]
What active effects are showing when you are playing? It's possible you may have chosen a perk that limits the effectiveness or you have an effect that is limiting the damage they can produce. Please attach a screenshot so I can have a look.

**Comment by JoliusI** [comment]
Okay I think i got it here.
Here is an screenshot of all my curret effects and my skills.
Do would it help if I took a screen shot of all my skills and effects individually
![Skärmbild 2021-04-26 152917](https://user-images.githubusercontent.com/81310776/116090938-ab141700-a6a4-11eb-8e2d-b01ac9beb023.png)
![Skärmbild 2021-04-26 153036](https://user-images.githubusercontent.com/81310776/116090993-b8310600-a6a4-11eb-8b35-ebd8b1f22034.png)
![Skärmbild 2021-04-26 153437](https://user-images.githubusercontent.com/81310776/116091300-f9c1b100-a6a4-11eb-9651-15d2bcaf2960.png)
![Skärmbild 2021-04-26 153100](https://user-images.githubusercontent.com/81310776/116091310-fc240b00-a6a4-11eb-99ae-7aedb9b6ca6c.png)
![Skärmbild 2021-04-26 152453](https://user-images.githubusercontent.com/81310776/116091403-10680800-a6a5-11eb-81cd-5a575b17f336.png)
![Skärmbild 2021-04-26 152559](https://user-images.githubusercontent.com/81310776/116091411-11993500-a6a5-11eb-90b3-9e16b7bcfd11.png)

**Comment by Althro** [comment]
Wait, how do you have vampire and beast blood at the same time.

**Comment by JoliusI** [comment]
I hade beast blood from one of the alchemy ingridients and then when i whent too harkon I got both. 
It did not take away the werebeast blood.
But the problem with the spell predate the werebeast/vampire thing so i dont know if it is that.

**Comment by Althro** [comment]
Hmmm. Can you upload your save please? I'll need the ess and skse file. Zip them up and drop them here.

**Comment by JoliusI** [comment]
Yeah sure, sorry for the delay
[Save257_886B53BE_0_4761697573204D6172697573_Tamriel_040438_20210425194534_35_1.zip](https://github.com/Althro/Tinvaak/files/6378297/Save257_886B53BE_0_4761697573204D6172697573_Tamriel_040438_20210425194534_35_1.zip)

**Comment by Althro** [comment]
Thanks for sending over your save. I just tested it in game and can confirm the issue with projectile based fire spells. I'll do some digging and see what's causing it.

**Comment by Althro** [comment]
I think I may have found the issue. The Mage stone from the standing stone mod CASSI appears to be affecting spells that have longer cast times. This issue has come up before with another spell Longstride. To fix this, you can either change your standing stone or disable CASSI. The latter does result in you needing to make a new save game.

Your player character has some really neat armor by the way.

**Comment by Althro** [comment]
This is fixed in 2.0 which I'm working on right now, hence the wontfix tag.

**Comment by JoliusI** [comment]
Thank you so much man.
Really appreciate you taking the time too help me with this.
Have a great day buddy 
:)

**Comment by JoliusI** [comment]
Do you have a patreon or something too support you and your efforts? 
:)

**Comment by Althro** [comment]
I do yes 😄 It's here: https://www.patreon.com/Althro
